development:
  adapter: postgresql
  encoding: unicode
  database: comic_development
  pool: 5
  host: localhost
  username: comic
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: comic_production
  pool: 5
  host: localhost
  username: comic
  password: